// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBftNnblvq6It1YZiKOuhXN_UIFmyCB5eA',
    appId: '1:1060120717156:web:75db685f14e888453a7c71',
    messagingSenderId: '1060120717156',
    projectId: 'social-net-97db1',
    authDomain: 'social-net-97db1.firebaseapp.com',
    storageBucket: 'social-net-97db1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYeZRzpDxjWlF6MrCqI6d6e2lUbPZU4b4',
    appId: '1:1060120717156:android:1c6e0efd5bcb2a1f3a7c71',
    messagingSenderId: '1060120717156',
    projectId: 'social-net-97db1',
    storageBucket: 'social-net-97db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7sysboSopxghOxxxJrhmDBTzm4DW3pI',
    appId: '1:1060120717156:ios:ea1c962aeea4dfc03a7c71',
    messagingSenderId: '1060120717156',
    projectId: 'social-net-97db1',
    storageBucket: 'social-net-97db1.appspot.com',
    iosClientId: '1060120717156-v6b1lms25o87mvn1d19ss90o2v258eoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7sysboSopxghOxxxJrhmDBTzm4DW3pI',
    appId: '1:1060120717156:ios:ea1c962aeea4dfc03a7c71',
    messagingSenderId: '1060120717156',
    projectId: 'social-net-97db1',
    storageBucket: 'social-net-97db1.appspot.com',
    iosClientId: '1060120717156-v6b1lms25o87mvn1d19ss90o2v258eoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNet',
  );
}
